[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "awsm_attention"
version = "0.1.0"
description = "Python wrapper for flash attention C/CUDA library"
requires-python = ">=3.8"
dependencies = ["torch"]

[tool.setuptools.package-data]
"awsm_attention.lib" = ["*.so"]